# Generated by Django 2.0.6 on 2018-06-18 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='название')),
                ('summary', models.TextField(max_length=200, verbose_name='краткое описание')),
                ('description', models.TextField(verbose_name='статья')),
            ],
        ),
    ]
