# Generated by Django 2.0.6 on 2018-06-18 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_auto_20180618_1758'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['name'], 'verbose_name': 'статья', 'verbose_name_plural': 'статьи'},
        ),
        migrations.AddField(
            model_name='article',
            name='image',
            field=models.ImageField(blank=True, default='', upload_to='articles/images', verbose_name='фотография'),
        ),
    ]
